### ISSUE TITLE
Implement supporting materials for presentations

### ISSUE THREAD

**Issue by acdha** [DCPython/dcpython-django#25]
We would like presenters to be able to upload their supporting materials (slides, pdfs, links, anything else?) to associate with their presentation. To get started we need the following models.

Two new models:

Presentation
==========

* Child of `Event`
* M2M against User (see #24) for speakers
* Title (text)
* Description (HTML)

Resources
========
* Link to one of (`Presentation`, `Event`) – use generic relations or just `event` and null-able `presentation` foreign keys?
* Type (choice field): link, embed, YouTube, …?
* Title (text)
* Content: TextField - arbitrary URL, HTML, etc.
* Template Tags:
  * `{% display_resource %}`: full display (e.g. generate YouTube embedded player treating content as video ID)
  * `{% resource_list %}`: displays unique icons for all resources in a collection. Handles the task of mapping icons for types (i.e. YouTube and Vimeo would just display a single video icon)

After adding Resources the YouTube support would be modified to always display from the database and have some mechanism for requesting a search of YouTube for videos for an event.

**Comment by dgreisen** [comment]
Hi @lauralorenz. Looks like you've made some good progress on this. @tgmiller5 is interested in helping with this issue. Is it ok if she takes a stab at some of the remaining work?

**Comment by lauralorenz** [comment]
hi @dgreisen, yes I totally dropped the ball so go for it @tgmiller5
