### ISSUE TITLE
Heroku costs $$$

### ISSUE THREAD

**Issue by aclark4life** [DCPython/dcpython-django#95]
Our platform credits from Heroku's generous donation ran out, so I've disabled paid services (e.g. SSL) until I can figure out a way to host the site for less $$.

**Comment by aclark4life** [comment]
CC: @kennethreitz Trying again here :smile: Feel free to say "no" to the donation request, just want to make sure we are reaching the right folks to make the request. Thank you!

**Comment by aclark4life** [comment]
Back to the free plan for now

**Comment by amyers2301** [comment]
If you need a cheap/free SSL cert, have you thought about StartCom?
https://cert.startcom.org/

I've used it in the past with good success.
