### ISSUE TITLE
Upgrade to Django 1.8

### ISSUE THREAD

**Issue by aclark4life** [DCPython/dcpython-django#96]
Some preliminary work has been done but there's more to do e.g. try removing comments in ``dcpython.app.models``:

```

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x104436500>
Traceback (most recent call last):
  File "/Users/alexclark/Developer/dcpython/dcpython-django/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Users/alexclark/Developer/dcpython/dcpython-django/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/alexclark/Developer/dcpython/dcpython-django/lib/python2.7/site-packages/django/core/management/base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/Users/alexclark/Developer/dcpython/dcpython-django/lib/python2.7/site-packages/django/core/management/base.py", line 528, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
app.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
app.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.

System check identified 4 issues (0 silenced).
```

**Comment by darkness51** [comment]
Use this to fix the error and then, create a migration to rename the database table:

```python
class Meta:
    db_table = 'auth_user'
```

**Comment by aclark4life** [comment]
@darkness51 Cool can you send a PR?

**Comment by aclark4life** [comment]
@DCPython/website Can anyone send a PR for this? :smile:

**Comment by ashu12166** [comment]
Sir I'm getting these error and the above solution are not fixing the error 

auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'Freelancer.groups'.
        HINT: Add or change a related_name argument to the definition for 'User.groups' or 'Freelancer.groups'.
auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'Freelancer.user_permissions'.
        HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'Freelancer.user_permissions'.
login.Freelancer.groups: (fields.E304) Reverse accessor for 'Freelancer.groups' clashes with reverse accessor for 'User.groups'.
        HINT: Add or change a related_name argument to the definition for 'Freelancer.groups' or 'User.groups'.
login.Freelancer.groups: (fields.E331) Field specifies a many-to-many relation through model 'login.Freelancer_groups', which has not been installed.
login.Freelancer.user_permissions: (fields.E304) Reverse accessor for 'Freelancer.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
        HINT: Add or change a related_name argument to the definition for 'Freelancer.user_permissions' or 'User.user_permissions'.
login.Freelancer.user_permissions: (fields.E331) Field specifies a many-to-many relation through model 'login.Freelancer_user_permissions', which has not been installed.


Freelancer is  the name of the custom  model ..
